name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]


env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-7.1
  DEVICE: montana
  DT_LINK: https://github.com/TeamWin/android_device_motorola_montana
  DT_PATH: device/xiaomi/montana
  TARGET: recoveryimage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST
             repo sync -j4
             git clone $DT_LINK
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch omni_$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && export LC_ALL=C && mka $TARGET
             
       - name: Upload recovery image
         run: |
              cd work/out/target/product/$DEVICE
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit recovery.img
