name: GSI - Erfan

on: [push]

env:
  ROM: MIUI
  ROM_LINK: https://211-95-34-2.ksyungslb.com/bigota.d.miui.com/21.1.20/miui_LAURUS_21.1.20_a5c6929058_10.0.zip?ksy_gslb_referer=https%3A%2F%2Fgithub.com%2FmooseIre%2Fupdate_miui_ota%2Fblob%2Fmaster%2FDevelop%2F%25E5%25B0%258F%25E7%25B1%25B3CC%25209e.md
  MIR: gof
  TZ: America/Sao_Paulo
  READ: Warning! This is A64 (Binder) based firmware.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x $ROM/initial.sh
              . $ROM/initial.sh
       
       - name: Clone ErfanGSI Source Code
         run: git clone https://github.com/yukosky/ErfanGSIs -b runner
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}
              
         run: |
               chmod +x $ROM/build.sh
               . $ROM/build.sh
               
       - name: Copy and rename AB build info
         run: cp ErfanGSIs/output/*AB*.txt AB.txt

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              TOKEN: ${{ secrets.TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}

         run: |
              python .github/workflows/robot.py
