name: GSI - Erfan

on: [push]
    
env:
  ROM: AncientOS
  ROM_LINK: https://ufpr.dl.sourceforge.net/project/ancientrom/mido/AncientOS-CIVILIZATION-v3.8-mido-PRIMEVAL-20200709-1544-GApps.zip
  MIR: wet
  TZ: America/Sao_Paulo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x $ROM/initial.sh
              . $ROM/initial.sh
       
       - name: Clone ErfanGSI Source Code
         run: git clone https://github.com/yukosky/ErfanGSIs -b runner
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}
              
         run: |
               chmod +x $ROM/build.sh
               . $ROM/build.sh
               
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*Aonly*.txt
              echo "- Aonly Up | AB Above -"
              cat ErfanGSIs/output/*-AB-*.txt
